### ISSUE TITLE
Overloads of GetStringAsync

### ISSUE THREAD

**Issue by mungojam** [FantasticFiasco/aws-signature-version-4#526]
**Is your feature request related to a problem? Please describe.**
The `GetStringAsync()` extension on HttpClient is exactly what I need, but it's not currently supported with this (super) package

**Describe the solution you'd like**
I'd like it to work just like the other overloads, taking the AWS credentials as a parameter

**Describe alternatives you've considered**
I can call `GetAsync()` instead but then I need to work a bit harder with the response status codes etc.

**Comment by FantasticFiasco** [comment]
I can look into what it would take to implement these overloads, but I cannot start until next week. I'll get back to you when I know more.

**Comment by FantasticFiasco** [comment]
Hi @mungojam.

When retrospecting regarding what I've been up to this year I unfortunately have to tell you that my engagements with my day-to-day employer has ramped up in intensity. I will still be able to keep my projects up-to-date regarding security issues and external dependencies due to automation, but even though I would love to implement this feature, because I think it's a good one that will increase the value of this project, I cannot give you a deadline, nor promise you that I ever will find the time to implement it.

Looking at alternatives, are you able to contribute the code to this project? Or are you working for a company that is making money and have the option to fund this project?

**Comment by FantasticFiasco** [comment]
A new version has now been released. Thank you for the contributions!
